# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.169
neo_version_range=[21.1.0,)
loader_version_range=[4,)
create_version = 6.0.5-92
create_version_range = [6.0.0,)
ponder_version = 1.0.50
flywheel_minecraft_version = 1.21.1
flywheel_version = 1.0.2
registrate_version = MC1.21-1.3.0+62

## Mod Properties
mod_id=cmparallelpipes
mod_name=Create More: Parallel Pipes
mod_license=MIT License
mod_version=1.0.0
mod_group_id=com.krei.cmparallelpipes
mod_authors=Krei, Brovv
mod_description=Allows you to have pipes that don't automatically connect with each other akin to encased pipes.